name: notepad_forwangtao_android
description: "汪涛的记事本 安卓版"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Flutter 本地化
  flutter_localizations:
    sdk: flutter
  # MaterialYou 动态颜色
  dynamic_color: ^1.7.0
  # FontAwesome 图标
  font_awesome_flutter: ^10.7.0
  # Riverpod 状态管理
  riverpod: ^2.6.1
  # 路由
  go_router: ^14.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true